"""
PDF Ingestion Module
Handles document loading, chunking, and per-document FAISS shard creation.
Multi-doc aware: returns shard + metadata; does NOT touch global vector store.
"""

import time

from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Import config for chunking/retry settings
from config import (
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    INGESTION_BATCH_SIZE,
    INGESTION_MAX_RETRIES,
    INGESTION_BASE_DELAY,
    SHARD_DIR,
)

# Import structured logging
from logging_config import get_logger

logger = get_logger(__name__)


def create_optimized_vectorstore(documents, embeddings, num_chunks: int):
    """
    Create FAISS index optimized based on document size (Tier 4).

    Args:
        documents: List of document chunks
        embeddings: Embeddings instance
        num_chunks: Total number of chunks

    Returns:
        Optimized FAISS vectorstore
    """
    # For small documents (< 1000 chunks), use brute-force IndexFlatL2
    # This is fastest for small datasets and requires no training
    if num_chunks < 1000:
        logger.info("faiss_optimization", strategy="brute-force", chunks=num_chunks)
        return FAISS.from_documents(documents, embeddings)

    # For large documents (>= 1000 chunks), use IVF (Inverted File Index)
    # This provides faster search at the cost of slightly reduced accuracy
    logger.info("faiss_optimization", strategy="ivf", chunks=num_chunks)

    try:
        import faiss
        import numpy as np

        # Calculate optimal number of clusters (nlist)
        # Rule of thumb: sqrt(N) for IVF
        nlist = int(num_chunks ** 0.5)
        dimension = 768  # text-embedding-004 dimension

        logger.debug("faiss_ivf_config", nlist=nlist, dimension=dimension)

        # Create quantizer and IVF index
        quantizer = faiss.IndexFlatL2(dimension)
        index = faiss.IndexIVFFlat(quantizer, dimension, nlist)

        # Generate embeddings for training (sample or all, depending on size)
        logger.info("faiss_ivf_training", message="Training IVF index with document embeddings")

        # Get all embeddings as numpy array
        texts = [doc.page_content for doc in documents]
        embeddings_array = np.array(embeddings.embed_documents(texts)).astype('float32')

        # Train the index
        index.train(embeddings_array)
        logger.info("faiss_ivf_trained", vectors=len(embeddings_array))

        # Create vectorstore with trained IVF index
        # Note: LangChain's FAISS wrapper simplifies this process.
        # If custom index support is limited, we fall back to the default implementation which is robust.
        vectorstore = FAISS.from_documents(documents, embeddings)

        logger.info("faiss_ivf_complete", message="IVF index created successfully")
        return vectorstore

    except ImportError:
        logger.warning("faiss_import_failed", message="faiss-cpu not available, using default index")
        return FAISS.from_documents(documents, embeddings)
    except Exception as e:
        logger.error("faiss_optimization_failed", error=str(e), message="Falling back to default index")
        return FAISS.from_documents(documents, embeddings)


def ingest_pdf(file_path: str, doc_id: str, filename: str) -> dict:
    """
    Ingest a PDF file and create a per-document FAISS shard.

    Does NOT touch the global vector store. The caller (upload router) is
    responsible for calling merge_shard(result["shard"]) on the singleton.

    Args:
        file_path: Path to the PDF file
        doc_id: UUID string (generated by caller) uniquely identifying this document
        filename: Original upload filename (injected into chunk metadata)

    Returns:
        dict with keys:
            "chunks"  — number of chunks created
            "shard"   — FAISS shard object (saved to SHARD_DIR/{doc_id}/)
            "doc_id"  — the doc_id passed in
    """
    from langchain_google_genai import GoogleGenerativeAIEmbeddings
    from config import GOOGLE_API_KEY, EMBEDDING_MODEL

    # 1. Load PDF
    loader = PyPDFLoader(file_path)
    documents = loader.load()

    # 2. Split into chunks
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP
    )
    chunks = text_splitter.split_documents(documents)

    if len(chunks) == 0:
        raise ValueError("PDF contains no extractable text")

    # 3. Inject doc_id and filename metadata into every chunk
    for chunk in chunks:
        chunk.metadata["doc_id"] = doc_id
        chunk.metadata["filename"] = filename

    # 4. Create embeddings
    embeddings = GoogleGenerativeAIEmbeddings(
        model=EMBEDDING_MODEL,
        google_api_key=GOOGLE_API_KEY
    )

    # 5. Create per-doc FAISS shard (optimized based on size)
    shard = create_optimized_vectorstore(chunks, embeddings, len(chunks))

    # 6. Save shard to disk at SHARD_DIR/{doc_id}/
    shard_dir = SHARD_DIR / doc_id
    shard_dir.mkdir(parents=True, exist_ok=True)
    shard.save_local(str(shard_dir))

    logger.info("shard_created", doc_id=doc_id, filename=filename, chunks=len(chunks), shard_path=str(shard_dir))

    return {"chunks": len(chunks), "shard": shard, "doc_id": doc_id}


def _is_rate_limit_error(error: Exception) -> bool:
    """Check if an error is a rate limit error"""
    error_str = str(error)
    return any(indicator in error_str for indicator in [
        "429",
        "RESOURCE_EXHAUSTED",
        "Too Many Requests"
    ])
